import { UUID } from "https://unpkg.com/uuidjs@^5";

export const products = [
  {
    id: UUID.generate(),
    name: 'Apple iPhone 14',
    img : 'https://ss7.vzw.com/is/image/VerizonWireless/apple-iphone-16-pro-natural-titanium?hei=262&fmt=webp',
    alt : 'Apple iPhone 14',
    brand : 'Apple',
    newPrice : 899.99,
    oldPrice : 999.99,
    discount : 10,
    size : '128GB',
    idealFor : 'Photography, Gaming, Everyday Use',
    rating : 4.8,
  },
  {
    id: UUID.generate(),
    name: 'Samsung Galaxy S23',
    img : 'https://imgs.search.brave.com/tYFjQ1i_p7POLddToLC0ZaXHC06kiXvSRmquLlg2CNs/rs:fit:0:180:1:0/g:ce/aHR0cHM6Ly93d3cu/OTEtY2RuLmNvbS9o/dWIvd3AtY29udGVu/dC91cGxvYWRzLzIw/MjMvMDUvU2Ftc3Vu/Zy1HYWxheHktUzIz/LUxpbWUuanBnP3Ry/PXctMjgwLGgtMTYw/LGMtMSxxLTcw',
    alt : 'Samsung Galaxy S23',
    brand : 'Samsung',
    newPrice : 799.99,
    oldPrice : 899.99,
    discount : 11,
    size : '256GB',
    idealFor : 'Photography, Gaming, Everyday Use',
    rating : 4.7,
  },
  {
    id: UUID.generate(),
    name: 'Google Pixel 7 Pro',
    img : 'https://imgs.search.brave.com/XqvDoddvPJkAxxyvFLvLweCOa8pOGRJekmjPyEm7wzI/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9mZG4y/LmdzbWFyZW5hLmNv/bS92di9waWNzL3Nh/bXN1bmcvc2Ftc3Vu/Zy1nYWxheHktajct/MjAxNy1zbS1qNzMw/LTIuanBn',
    alt : 'Google Pixel 7 Pro',
    brand : 'Google',
    newPrice : 899.00,
    oldPrice : 999.00,
    discount : 10,
    size : '128GB',
    idealFor : 'Photography, Everyday Use',
    rating : 4.6,
  },
  {
    id: UUID.generate(),
    name: 'OnePlus 11',
    img : 'https://imgs.search.brave.com/9omeHKqEtFHTakQL7NwZFgU_3PsBhfRwzUe1dwvYylU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF84/ODE1OTEtTUxBODQ1/NDg4MjI4NjRfMDUy/MDI1LU8ud2VicA',
    alt : 'OnePlus 11',
    brand : 'OnePlus',
    newPrice : 749.99,
    oldPrice : 849.99,
    discount : 12,
    size : '256GB',
    idealFor : 'Gaming, Everyday Use',
    rating : 4.5,
  }
]